### ISSUE TITLE
eqeqeq should be disabled for comparisons with null or undefined

### ISSUE THREAD

**Issue by Aakodal** [typescord/beauty#7]
The rule `eqeqeq` should allow `==` and `!=` with null or undefined.
```diff
- eqeqeq: ["error", "always"],
+ eqeqeq: ["error", "always", {"null": "ignore"}],
```

But actually, doing so will make a conflict between this rule and `unicorn/no-null`. We then would have to disable it.

**Comment by Mesteery** [comment]
Can we use `undefined` instead of `null` ?

**Comment by Aakodal** [comment]
Yes, we can, it's just a bit longer

**Comment by Mesteery** [comment]
Yes, but we have another rule that force to use `undefined` instead of `null`.

**Comment by Aakodal** [comment]
Then let's keep undefined, but we should disallow eqeqeq for null nonetheless as it also covers undefined.

**Comment by Mesteery** [comment]
`eqeqeq: ["error", "always", {"undefined": "ignore"}]` "?
